config/routes.rb
Lensesly::Application.routes.draw do

  get "beauty_competition/index"

  scope :controller => :content do 
    get '/opticiens' => :opticians, :as => :loli
    get '/aide' => :help, :as => :help
    get '/a-propos' => :about, :as => :aboute
    get '/contact' => :contact, :as => :contact
    get '/concours' => :concours, :as => :concours
    get '/mentions' => :mention
    get '/conditions-generales' => :conditions
    get '/ecart-pupillaire' => :pupilaire
    get '/aide' => :aide
  end

  scope :controller => :beauty_competition, :path => '/beauty' do
    post '/create' => :add_form
  end

  match '/conditions' => 'content#conditions', :as => :conditions

  
  post '/nws/post' => 'newsletters#create_ajax'

  mount Spree::Core::Engine, :at => '/'

  match '/adm/ajx/dl' => 'spree/products#ajax_delete_product'
  match '/adm/ajx/switch' => 'spree/products#switch_taxon'

  match '/test' => 'spree/products#test'
  match '/test_taxon/*id' => 'spree/taxons#test'

  

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :mail
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsletters }
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/new
  # GET /newsletters/new.json
  def new
    @newsletter = Newsletter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/1/edit
  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(params[:newsletter])

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render json: @newsletter, status: :created, location: @newsletter }
      else
        format.html { render action: "new" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_ajax
    @newsletter = Newsletter.create(:mail => params[:dt])
    render :json => {:success => :true }
  end

  # PUT /newsletters/1
  # PUT /newsletters/1.json
  def update
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      if @newsletter.update_attributes(params[:newsletter])
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<h1>Listing newsletters</h1>

<table>
  <tr>
    <th>Mail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @newsletters.each do |newsletter| %>
  <tr>
    <td><%= newsletter.mail %></td>
    <td><%= link_to 'Show', newsletter %></td>
    <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
    <td><%= link_to 'Destroy', newsletter, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mail:</b>
  <%= @newsletter.mail %>
</p>


<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>